[theme]
base="dark"

# Primary accent for interactive elements
primaryColor = '#0000FF'

# Background color for the main content area
backgroundColor = '#00008b'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#31aaaa'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


